// "Bintang yang Hilang dari Langit Meadowfar" / "The Lost Stars of Meadowfar"
// Act I (12 chapters): the missing stars. Act II (12 chapters): the lantern
// keeper Sela, who took them out of loneliness. Act III (12 chapters): the
// silent north wind and the wolves who lost their song. Indonesian and English.

export interface Chapter {
  bab: number;
  judul: string;
  teks: string;
  judulEn: string;
  teksEn: string;
  // What the elder asks you to do next — turns a read-only chapter into a deed.
  tugas: string;
  tugasEn: string;
}

// Each chapter points at the quest kind the elder wants next, so the story and
// the gameplay rotation actually agree with each other.
export const CHAPTER_TASK: Record<number, "collect" | "race" | "treasure" | "delivery" | "shard"> = {
  1: "collect", 2: "collect", 3: "race", 4: "treasure",
  5: "treasure", 6: "delivery", 7: "shard", 8: "collect",
  9: "race", 10: "delivery", 11: "shard", 12: "shard",
  13: "collect", 14: "collect", 15: "delivery", 16: "race",
  17: "treasure", 18: "delivery", 19: "collect", 20: "collect",
  21: "shard", 22: "collect", 23: "delivery", 24: "shard",
  25: "collect", 26: "race", 27: "treasure", 28: "delivery",
  29: "collect", 30: "race", 31: "shard", 32: "treasure",
  33: "delivery", 34: "collect", 35: "race", 36: "shard",
};

export const STORY: Chapter[] = [
  {
    bab: 1,
    judul: "Langit yang meredup",
    teks: "Dahulu, langit Meadowfar penuh bintang yang bernyanyi setiap malam. Namun suatu pagi, para tetua terbangun dan menghitung: dua belas bintang paling terang telah hilang. Sejak itu, kami menunggu seorang penjelajah kecil yang berani berjalan sampai ke tepi dunia.",
    judulEn: "The sky that dimmed",
    teksEn: "Long ago, the sky above Meadowfar was full of stars that sang every night. But one morning the elders woke and counted: the twelve brightest stars were gone. Ever since, we have waited for a small explorer brave enough to walk to the edge of the world.",
    tugas: "Mulailah dari yang sederhana: kumpulkan serpihan berkilau di padang ini.",
    tugasEn: "Start simple: gather the glittering pieces scattered across this meadow.",
  },
  {
    bab: 2,
    judul: "Jejak cahaya pertama",
    teks: "Bintang tidak jatuh begitu saja. Mereka pecah menjadi serpihan kecil — bintang emas, buah beri yang berpendar, kristal biru. Setiap kali kamu mengumpulkannya, satu serpihan kembali ke langit. Kamu sudah membantu lebih dari yang kamu tahu.",
    judulEn: "The first trail of light",
    teksEn: "Stars do not simply fall. They shatter into tiny pieces — golden stars, glowing berries, blue crystals. Every time you gather one, a piece returns to the sky. You have already helped more than you know.",
    tugas: "Kumpulkan satu genggam serpihan lagi — tiap satu membuat langit sedikit terang.",
    tugasEn: "Gather one more handful of pieces — each one brightens the sky a little.",
  },
  {
    bab: 3,
    judul: "Kelinci yang tahu jalan",
    teks: "Perhatikan kelinci-kelinci putih itu. Mereka dulu tidur di bawah cahaya bintang, dan kini mereka melompat-lompat gelisah mencarinya. Konon, mereka selalu berlari ke arah serpihan yang paling dekat. Ikuti mereka bila kamu tersesat.",
    judulEn: "The rabbits who know the way",
    teksEn: "Watch the white rabbits. They used to sleep beneath the starlight, and now they hop about restlessly searching for it. They say the rabbits always run toward the nearest star piece. Follow them if you ever feel lost.",
    tugas: "Berlarilah secepat kelinci: lewati semua gerbang cahaya sebelum waktu habis.",
    tugasEn: "Run as fast as a rabbit: pass every gate of light before the time runs out.",
  },
  {
    bab: 4,
    judul: "Angin dari gurun",
    teks: "Jauh di sana, rumput berubah menjadi pasir keemasan. Di gurun itu, satu bintang jatuh dan pasirnya masih hangat sampai sekarang. Bawalah air dan keberanian — gurun luas, tapi tidak pernah kejam pada anak yang baik hati.",
    judulEn: "Wind from the desert",
    teksEn: "Far away, the grass turns into golden sand. One star fell in that desert, and the sand is still warm to this day. Bring water and courage — the desert is vast, but it is never cruel to a kind-hearted child.",
    tugas: "Carilah peti bertanda X — di dalamnya tersimpan hangatnya bintang gurun.",
    tugasEn: "Look for the chest marked with an X — the desert star's warmth is kept inside.",
  },
  {
    bab: 5,
    judul: "Nyanyian salju",
    teks: "Ke arah yang lain, dunia menjadi putih dan sunyi. Di padang salju, suara paling kecil pun terdengar seperti lonceng. Para tetua percaya satu bintang bersembunyi di sana, membeku, menunggu seseorang yang cukup hangat hatinya untuk menemukannya.",
    judulEn: "The song of the snow",
    teksEn: "In the other direction, the world turns white and silent. On the snowfield, even the smallest sound rings like a bell. The elders believe one star hides there, frozen, waiting for someone warm-hearted enough to find it.",
    tugas: "Temukan peti yang terkubur — bintang beku itu butuh tangan yang hangat.",
    tugasEn: "Find the buried chest — that frozen star needs a warm pair of hands.",
  },
  {
    bab: 6,
    judul: "Setengah perjalanan",
    teks: "Enam bab sudah kamu dengar, dan langit mulai berubah. Lihatlah malam ini — ada kerlip kecil yang kemarin belum ada. Itu karena kamu. Istirahatlah di desa kami kapan pun kakimu lelah; pintu kami selalu terbuka.",
    judulEn: "Halfway there",
    teksEn: "You have heard six chapters now, and the sky is beginning to change. Look tonight — there is a small twinkle that was not there yesterday. That is because of you. Rest in our village whenever your feet grow tired; our doors are always open.",
    tugas: "Bantu kami sedikit: antarkan sebuah paket ke tempat bertanda hijau.",
    tugasEn: "Help us in return: carry a package to the spot marked in green.",
  },
  {
    bab: 7,
    judul: "Danau yang memantulkan langit",
    teks: "Danau-danau di lembah bukan air biasa. Saat malam tiba, permukaannya memantulkan langit seperti cermin, dan bintang yang hilang kadang terlihat di pantulan itu meski tidak ada di atas. Para tetua menyebutnya 'jendela langit'.",
    judulEn: "The lake that mirrors the sky",
    teksEn: "The lakes in the valleys are no ordinary water. When night falls, their surface mirrors the sky, and sometimes the lost stars appear in the reflection even when they are missing above. The elders call them 'windows to the sky'.",
    tugas: "Bawalah pecahan bintang ke altar batu, lalu letakkan pelan-pelan.",
    tugasEn: "Carry a star shard to the stone altar, and set it down gently.",
  },
  {
    bab: 8,
    judul: "Penjaga kecil bercahaya",
    teks: "Kunang-kunang adalah anak-anak bintang. Mereka keluar setiap malam untuk menghibur langit yang kesepian. Kalau kamu berjalan malam hari dengan lentera, mereka akan mengiringimu — mereka mengira lenteramu adalah saudara mereka.",
    judulEn: "The little glowing keepers",
    teksEn: "Fireflies are the children of the stars. They come out every night to comfort the lonely sky. If you walk at night carrying a lantern, they will travel beside you — they believe your lantern is their sibling.",
    tugas: "Kumpulkan serpihan saat malam, ditemani kunang-kunang dan lenteramu.",
    tugasEn: "Gather pieces after dark, with the fireflies and your lantern for company.",
  },
  {
    bab: 9,
    judul: "Kisah sang satria",
    teks: "Dahulu ada satria yang mencoba mengembalikan bintang dengan pedang dan perisai. Ia gagal. Bintang tidak bisa dipaksa pulang — mereka hanya kembali untuk tawa, langkah kecil, dan tangan yang mengumpulkan serpihan dengan sabar. Karena itulah kami menunggumu, bukan pasukan.",
    judulEn: "The tale of the knight",
    teksEn: "Once, a knight tried to bring the stars back with a sword and shield. He failed. Stars cannot be forced home — they only return for laughter, small footsteps, and hands that gather the pieces patiently. That is why we waited for you, not an army.",
    tugas: "Tunjukkan cara yang benar: menang balapan dengan kaki ringan, bukan pedang.",
    tugasEn: "Show the better way: win a race on light feet, not with a sword.",
  },
  {
    bab: 10,
    judul: "Peta yang tidak pernah selesai",
    teks: "Dunia ini tumbuh mengikuti langkahmu. Ke mana pun kamu berjalan, bukit baru bangun dari tidurnya dan pohon baru menegakkan punggungnya. Tidak ada tepi dunia — yang ada hanya bagian yang belum kamu sapa.",
    judulEn: "The map that is never finished",
    teksEn: "This world grows with your footsteps. Wherever you walk, new hills wake from their sleep and new trees straighten their backs. There is no edge of the world — only places you have not yet said hello to.",
    tugas: "Berjalanlah ke tempat yang belum kamu sapa, dan antarkan paket ke sana.",
    tugasEn: "Walk somewhere you have not greeted yet, and deliver a package there.",
  },
  {
    bab: 11,
    judul: "Malam paling terang",
    teks: "Sebelas bintang sudah pulang. Satu yang terakhir adalah bintang paling kecil dan paling pemalu. Ia tidak bersembunyi di gurun, salju, atau danau. Ia mengikutimu diam-diam sejak langkah pertamamu, menunggu kamu selesai mendengar semua kisah kami.",
    judulEn: "The brightest night",
    teksEn: "Eleven stars have come home. The last one is the smallest and shyest star of all. It is not hiding in the desert, the snow, or the lakes. It has been quietly following you since your very first step, waiting for you to finish hearing all our stories.",
    tugas: "Antarkan pecahan terakhir ke altar — bintang pemalu itu akan mengikutimu.",
    tugasEn: "Bring the last shard to the altar — the shy star will follow you there.",
  },
  {
    bab: 12,
    judul: "Penjaga bintang",
    teks: "Sekarang menoleh ke atas. Bintang kecil itu ada di langit lagi — pulang tepat saat kamu mendengar kata-kata ini. Langit Meadowfar utuh kembali, dan mulai malam ini semua bintang bersinar untukmu, sang Penjaga Bintang. Kisah selesai, tapi padang ini selamanya rumahmu.",
    judulEn: "Keeper of the stars",
    teksEn: "Now look up. The little star is back in the sky — it returned the very moment you heard these words. The sky of Meadowfar is whole again, and from tonight on, every star shines for you, Keeper of the Stars. The story is finished, but this meadow is your home forever.",
    tugas: "Istirahatlah sebentar di rumah pohon. Besok pagi, Tetua Wren ingin bicara lagi.",
    tugasEn: "Rest a while at the tree house. Tomorrow morning, Elder Wren wants to talk again.",
  },
  // ---------------- Act II: The Keeper Beneath the Mountain ----------------
  {
    bab: 13,
    judul: "Surat tanpa nama",
    teks: "Pagi ini ada surat terselip di pintu rumah pohonmu. Kertasnya dingin seperti batu gunung, dan tintanya berkilau biru. Isinya hanya satu kalimat: \"Aku yang mengambil bintang-bintang itu, dan aku menyesal.\" Tetua Wren membacanya dua kali, lalu diam lama sekali.",
    judulEn: "A letter with no name",
    teksEn: "This morning a letter was tucked into the door of your tree house. The paper was cold as mountain stone, and the ink shimmered blue. It held a single sentence: \"I am the one who took the stars, and I am sorry.\" Elder Wren read it twice, then said nothing for a long while.",
    tugas: "Tinta biru itu berbau kristal. Kumpulkan serpihan kristal untuk dibandingkan.",
    tugasEn: "The blue ink smells of crystal. Collect crystal pieces so the elders can compare them.",
  },
  {
    bab: 14,
    judul: "Pembuat peta Tomas",
    teks: "Tomas, pembuat peta tua di desa sebelah, mengenali warna tinta itu. \"Hanya ada satu tempat yang kristalnya menyala sebiru ini,\" katanya sambil membuka gulungan peta yang sudah robek di tepinya. \"Gua Kristal. Tapi separuh petaku hilang bertahun-tahun lalu, tepat di malam bintang menghilang.\"",
    judulEn: "Tomas the mapmaker",
    teksEn: "Tomas, the old mapmaker from the next village, recognised the colour of that ink. \"Only one place has crystals that burn this blue,\" he said, unrolling a map torn along one edge. \"The Crystal Cave. But half of my map went missing years ago, on the very night the stars disappeared.\"",
    tugas: "Masuki Gua Kristal dan bawa pulang permata biru sebagai bukti.",
    tugasEn: "Enter the Crystal Cave and bring back a blue gem as proof.",
  },
  {
    bab: 15,
    judul: "Ukiran di dinding gua",
    teks: "Di balik tirai kristal, kamu menemukan ukiran yang tidak pernah dilihat siapa pun: seorang gadis memegang lentera, berdiri sendirian di puncak gunung, dikelilingi dua belas titik cahaya. Di bawahnya tertulis sebuah nama yang hampir terhapus: Sela.",
    judulEn: "Carvings on the cave wall",
    teksEn: "Behind a curtain of crystal you found carvings no one had ever seen: a girl holding a lantern, standing alone on a mountaintop, surrounded by twelve points of light. Beneath it, a name almost worn away: Sela.",
    tugas: "Tetua perlu tahu siapa Sela. Antarkan salinan ukiran itu ke desa terdekat.",
    tugasEn: "The elders need to know who Sela is. Deliver a copy of the carving to the nearest village.",
  },
  {
    bab: 16,
    judul: "Penjaga lentera",
    teks: "Nenek tertua di desa itu menangis mendengar nama Sela. Dulu, Sela adalah penjaga lentera yang menyalakan jalan bagi pelancong di pegunungan. Ketika jalan baru dibangun di lembah, tidak ada lagi yang mendaki. Lenteranya tetap menyala, tapi tidak ada yang datang, dan tidak ada yang ingat mengucapkan terima kasih.",
    judulEn: "The lantern keeper",
    teksEn: "The oldest grandmother in that village wept when she heard Sela's name. Long ago, Sela was the lantern keeper who lit the path for travellers in the mountains. When a new road was built through the valley, nobody climbed anymore. Her lantern kept burning, but no one came, and no one remembered to say thank you.",
    tugas: "Jalan gunung lama masih ada. Tempuh jalurnya secepat mungkin sebelum gelap.",
    tugasEn: "The old mountain path is still there. Run its course as fast as you can before dark.",
  },
  {
    bab: 17,
    judul: "Aula yang tertutup debu",
    teks: "Jalur itu berakhir di Aula Gunung. Rak-raknya penuh buku catatan tamu, dan halaman terakhirnya bertanggal hari yang sama dengan hilangnya bintang. Di sana, dengan tulisan tangan kecil: \"Jika tidak ada yang melihat cahayaku, akan kupinjam cahaya langit, supaya aku tidak sendirian.\"",
    judulEn: "The hall under the dust",
    teksEn: "The path ended at the Mountain Hall. Its shelves were full of guest books, and the last page was dated the same day the stars vanished. There, in small handwriting: \"If no one sees my light, I will borrow the light of the sky, so I am not alone.\"",
    tugas: "Naiki tangga aula ke balkon dan buka peti yang sudah lama terkunci.",
    tugasEn: "Climb the hall stairs to the balcony and open the chest that has been locked for years.",
  },
  {
    bab: 18,
    judul: "Separuh peta yang hilang",
    teks: "Di dalam peti ada separuh peta Tomas, dilipat rapi dan disimpan baik-baik. Sela tidak mencurinya untuk menyakiti. Ia menyimpannya karena hanya peta itu yang menunjukkan jalan ke rumahnya, dan ia berharap suatu hari ada yang cukup peduli untuk mencarinya.",
    judulEn: "The missing half of the map",
    teksEn: "Inside the chest was the other half of Tomas's map, folded neatly and kept safe. Sela had not stolen it to hurt anyone. She kept it because it was the only map that showed the way to her home, and she hoped that one day someone would care enough to come looking.",
    tugas: "Kembalikan peta itu ke Tomas. Ia sudah menunggu terlalu lama.",
    tugasEn: "Return the map to Tomas. He has waited far too long.",
  },
  {
    bab: 19,
    judul: "Latihan di arena",
    teks: "Peta lengkap Tomas menunjukkan jalan ke puncak tertinggi, tapi jalannya dijaga slime-slime penjaga yang dulu diberi tugas oleh Sela: jangan biarkan siapa pun lewat. Mereka tidak jahat, hanya setia pada perintah lama. Para pelatih di Arena Latihan bisa mengajarimu cara meletuskan mereka dengan lembut.",
    judulEn: "Training in the arena",
    teksEn: "Tomas's completed map shows the way to the highest peak, but the path is guarded by slimes Sela once gave a single order: let no one through. They are not wicked, just loyal to an old command. The trainers at the Training Arena can teach you how to pop them gently.",
    tugas: "Berlatihlah di Arena Latihan sampai tongkat gelembungmu terasa ringan.",
    tugasEn: "Train at the Training Arena until your bubble wand feels light in your hand.",
  },
  {
    bab: 20,
    judul: "Bekal perjalanan panjang",
    teks: "\"Tidak ada yang mendaki gunung dengan perut kosong,\" kata Tetua Wren sambil menyiapkan keranjang. Pendakian ke puncak Sela butuh sehari penuh. Beri dari semak, jamur dari hutan yang teduh, bunga dari padang: semuanya bisa diracik jadi bekal yang menghangatkan.",
    judulEn: "Supplies for a long road",
    teksEn: "\"Nobody climbs a mountain on an empty stomach,\" said Elder Wren, packing a basket. The climb to Sela's peak takes a full day. Berries from the bushes, mushrooms from the shady woods, flowers from the meadow: all of it can be cooked into food that keeps you warm.",
    tugas: "Petik bahan di alam dan racik sup jamur atau teh bunga untuk perjalanan.",
    tugasEn: "Gather ingredients in the wild and craft mushroom soup or flower tea for the journey.",
  },
  {
    bab: 21,
    judul: "Tunggangan dari lembah",
    teks: "Kuda-kuda liar di lembah dulu mengantar para pelancong ke lentera Sela. Mereka masih ingat jalannya. Jika kamu mendekat dengan tenang, salah satu dari mereka akan membiarkanmu naik dan membawamu lebih jauh daripada kakimu sendiri.",
    judulEn: "A ride from the valley",
    teksEn: "The wild horses of the valley once carried travellers up to Sela's lantern. They still remember the way. If you walk up to them calmly, one of them will let you climb on and carry you further than your own feet could.",
    tugas: "Tunggangi hewan liar dan capai altar bintang di kaki gunung.",
    tugasEn: "Ride a wild animal and reach the star altar at the foot of the mountain.",
  },
  {
    bab: 22,
    judul: "Lentera di puncak",
    teks: "Di puncak, lentera Sela masih menyala redup. Sela sendiri duduk di sampingnya, jauh lebih kecil daripada yang kamu bayangkan, memeluk lututnya. Di sekelilingnya, dua belas bintang pinjaman berputar pelan. \"Kamu datang,\" bisiknya. \"Sudah lama sekali tidak ada yang datang.\"",
    judulEn: "The lantern on the peak",
    teksEn: "At the summit, Sela's lantern still glowed faintly. Sela herself sat beside it, much smaller than you had imagined, hugging her knees. Around her, twelve borrowed stars circled slowly. \"You came,\" she whispered. \"It has been so long since anyone came.\"",
    tugas: "Jangan terburu-buru. Kumpulkan cahaya kecil di puncak dan duduklah bersamanya.",
    tugasEn: "Do not hurry. Gather the small lights on the peak and sit with her a while.",
  },
  {
    bab: 23,
    judul: "Pilihan Sela",
    teks: "Kamu tidak memarahinya, dan kamu tidak memaksanya. Kamu hanya bercerita tentang desa-desa, tentang Tomas yang kembali tersenyum, tentang nenek yang masih ingat namanya. Perlahan, Sela membuka tangannya. \"Kalau aku mengembalikan bintang-bintang ini,\" tanyanya, \"apakah masih ada yang akan datang?\"",
    judulEn: "Sela's choice",
    teksEn: "You did not scold her, and you did not force her. You simply told her about the villages, about Tomas smiling again, about the grandmother who still remembered her name. Slowly, Sela opened her hands. \"If I give the stars back,\" she asked, \"will anyone still come?\"",
    tugas: "Berikan jawabanmu dengan perbuatan: antarkan undangan dari semua desa kepadanya.",
    tugasEn: "Answer her with deeds: deliver an invitation from every village to her door.",
  },
  {
    bab: 24,
    judul: "Dua penjaga, satu langit",
    teks: "Malam itu, dua belas bintang pinjaman naik kembali ke langit, dan lentera Sela menyala paling terang di seluruh pegunungan. Sekarang jalan gunung ramai lagi: anak-anak mendaki untuk mendengar ceritanya, dan Sela menyalakan jalan untuk mereka setiap senja. Langit punya dua penjaga sekarang, dan tidak ada yang sendirian lagi.",
    judulEn: "Two keepers, one sky",
    teksEn: "That night the twelve borrowed stars rose back into the sky, and Sela's lantern burned brighter than any light in the mountains. The mountain path is busy again: children climb to hear her stories, and Sela lights the way for them every dusk. The sky has two keepers now, and no one is alone anymore.",
    tugas: "Rayakan bersama temanmu, lalu kembali ke tetua: angin dari utara membawa kabar baru.",
    tugasEn: "Celebrate with a friend, then return to the elder: the north wind is bringing new word.",
  },
  {
    bab: 25,
    judul: "Angin yang berhenti bernyanyi",
    teks: "Suatu pagi, angin utara tidak lagi bersiul di sela pepohonan. Daun-daun diam, kincir desa berhenti, dan burung-burung terbang rendah dengan bingung. Tetua menatap ke arah pegunungan salju. \"Angin utara selalu bernyanyi bersama para serigala,\" katanya pelan. \"Kalau angin diam, berarti para serigala juga diam.\"",
    judulEn: "The wind that stopped singing",
    teksEn: "One morning the north wind no longer whistled through the trees. The leaves were still, the village windmills stopped, and the birds flew low and confused. The elder looked toward the snowy mountains. \"The north wind always sings with the wolves,\" she said softly. \"If the wind is silent, the wolves are silent too.\"",
    tugas: "Kumpulkan bulu-bulu yang jatuh di padang untuk tahu dari mana angin terakhir bertiup.",
    tugasEn: "Gather the fallen feathers in the meadow to learn where the last wind blew from.",
  },
  {
    bab: 26,
    judul: "Rubah yang cepat",
    teks: "Di tepi hutan, seekor rubah merah memperhatikanmu dari balik semak. Ia tidak lari. \"Aku tahu jalan ke utara,\" katanya dengan mata berkilat, \"tapi aku hanya menunjukkannya kepada yang bisa mengejarku.\" Lalu ia melesat, ekornya seperti nyala api kecil di antara pohon.",
    judulEn: "The quick fox",
    teksEn: "At the edge of the forest a red fox watched you from behind a bush. It did not run. \"I know the way north,\" it said, eyes glinting, \"but I only show it to someone who can keep up.\" Then it darted off, its tail like a small flame between the trees.",
    tugas: "Ikuti balapan melewati semua gerbang sebelum waktu habis.",
    tugasEn: "Run the race through every gate before time runs out.",
  },
  {
    bab: 27,
    judul: "Jejak di bawah salju",
    teks: "Rubah itu berhenti di batas salju dan menunjuk jejak kaki besar yang setengah tertutup. \"Serigala,\" bisiknya. \"Mereka menyembunyikan sesuatu di sini sebelum menghilang.\" Di bawah salju ada kotak kayu tua yang diikat tali kulit, dan di dalamnya sebuah peluit dari tulang, retak di tengahnya.",
    judulEn: "Tracks under the snow",
    teksEn: "The fox stopped at the snow line and pointed at large, half-buried paw prints. \"Wolves,\" it whispered. \"They hid something here before they disappeared.\" Under the snow lay an old wooden box tied with leather cord, and inside it a bone whistle, cracked down the middle.",
    tugas: "Cari harta yang tersembunyi dengan mengikuti petunjuk di peta.",
    tugasEn: "Find the hidden treasure by following the clue on the map.",
  },
  {
    bab: 28,
    judul: "Anjing kereta dari utara",
    teks: "Di desa salju, para anjing husky menarik kereta berisi kayu bakar, tetapi mereka tampak lelah. \"Tanpa angin utara, salju tidak pernah memadat,\" kata pengemudi kereta. \"Kaki anjing-anjing kami tenggelam setiap langkah.\" Ia memintamu membawa selimut dan makanan ke pos-pos di sepanjang jalan.",
    judulEn: "The sled dogs of the north",
    teksEn: "In the snow village the huskies pulled sleds of firewood, but they looked tired. \"Without the north wind the snow never packs down,\" said the sled driver. \"Our dogs sink with every step.\" She asked you to carry blankets and food to the posts along the trail.",
    tugas: "Antarkan paket ke penduduk yang membutuhkannya.",
    tugasEn: "Deliver the parcel to the villager who needs it.",
  },
  {
    bab: 29,
    judul: "Peluit yang retak",
    teks: "Pandai kayu desa memeriksa peluit tulang itu. \"Ini peluit pemanggil angin,\" katanya takjub. \"Hanya bisa diperbaiki dengan getah pohon tua, lumut perak, dan batu yang pernah disentuh petir.\" Ia menggambarkan tempat-tempat itu di selembar kertas dan memberikannya kepadamu.",
    judulEn: "The cracked whistle",
    teksEn: "The village woodworker examined the bone whistle. \"This is a wind-calling whistle,\" he said in wonder. \"It can only be mended with sap from an old tree, silver moss, and a stone that lightning once touched.\" He sketched the places on a scrap of paper and handed it to you.",
    tugas: "Kumpulkan bahan-bahan di alam untuk memperbaiki peluit.",
    tugasEn: "Gather materials in the wild to mend the whistle.",
  },
  {
    bab: 30,
    judul: "Serigala pertama",
    teks: "Di lereng gunung, seekor serigala abu-abu berdiri di atas batu. Ia kurus dan diam, dan ketika kamu meniup peluit yang sudah diperbaiki, hanya keluar suara serak. Serigala itu memiringkan kepalanya, lalu berlari menanjak, berhenti sesekali untuk memastikan kamu mengikutinya.",
    judulEn: "The first wolf",
    teksEn: "On the mountainside a grey wolf stood on a rock. It was thin and silent, and when you blew the mended whistle, only a hoarse sound came out. The wolf tilted its head, then ran uphill, stopping now and then to make sure you were following.",
    tugas: "Ikuti serigala itu: selesaikan balapan melewati gerbang-gerbang di lereng.",
    tugasEn: "Follow the wolf: finish the race through the gates on the slope.",
  },
  {
    bab: 31,
    judul: "Gua kawanan",
    teks: "Serigala itu membawamu ke gua di balik air terjun beku. Di dalamnya seluruh kawanan berbaring rapat, terlalu lemah untuk melolong. Pemimpin mereka, serigala tua bernama Arun, membuka satu mata. \"Suara kami diambil,\" katanya. \"Tertidur di dalam kristal-kristal yang jatuh dari langit malam itu.\"",
    judulEn: "The pack's cave",
    teksEn: "The wolf led you to a cave behind a frozen waterfall. Inside, the whole pack lay close together, too weak to howl. Their leader, an old wolf named Arun, opened one eye. \"Our voices were taken,\" he said. \"They sleep inside the crystals that fell from the sky that night.\"",
    tugas: "Temukan pecahan kristal yang menyimpan suara kawanan.",
    tugasEn: "Find the crystal shards that hold the pack's voices.",
  },
  {
    bab: 32,
    judul: "Kristal di dasar danau",
    teks: "Satu kristal terakhir tenggelam di danau yang dulu jernih. Sela, yang datang dari puncaknya dengan lentera, menerangi air untukmu. \"Aku juga pernah kehilangan suaraku,\" katanya. \"Waktu itu aku terlalu lama sendirian. Mungkin para serigala hanya butuh ditemukan.\"",
    judulEn: "The crystal in the lake bed",
    teksEn: "One last crystal had sunk into a lake that was once clear. Sela, who came down from her peak with her lantern, lit the water for you. \"I lost my voice once too,\" she said. \"Back then I had been alone too long. Maybe the wolves just need to be found.\"",
    tugas: "Cari harta tersembunyi di dekat air dengan bantuan cahaya Sela.",
    tugasEn: "Search for the hidden treasure near the water with Sela's light.",
  },
  {
    bab: 33,
    judul: "Makanan untuk kawanan",
    teks: "Kristal-kristal mulai berdengung, tetapi kawanan terlalu lemah untuk menerima suaranya kembali. Desa-desa yang dulu takut pada serigala kini berdebat. Lalu Tomas, anak yang dulu kamu tolong, berdiri. \"Mereka menjaga hutan kita dari jauh selama bertahun-tahun,\" katanya. \"Sekarang giliran kita.\"",
    judulEn: "Food for the pack",
    teksEn: "The crystals began to hum, but the pack was too weak to take their voices back. The villages that once feared wolves argued. Then Tomas, the child you once helped, stood up. \"They guarded our forest from afar for years,\" he said. \"Now it is our turn.\"",
    tugas: "Antarkan bekal dari desa ke gua kawanan.",
    tugasEn: "Carry supplies from the village to the pack's cave.",
  },
  {
    bab: 34,
    judul: "Anjing kecil pemberani",
    teks: "Seekor anjing shiba dari desa lembah ikut diam-diam di belakangmu sepanjang jalan. Saat badai salju datang, ia yang menemukan jalan pulang dengan hidungnya, dan ia yang menggali bunga-bunga es yang dibutuhkan untuk menghangatkan kawanan. Anak-anak desa menamainya Kiko.",
    judulEn: "The brave little dog",
    teksEn: "A shiba dog from the valley village had quietly followed you the whole way. When a snowstorm came, it was the one that sniffed out the way home, and it was the one that dug up the frost flowers needed to warm the pack. The village children named it Kiko.",
    tugas: "Bersama Kiko, kumpulkan bunga es dan cahaya kecil di salju.",
    tugasEn: "With Kiko, gather frost flowers and small lights in the snow.",
  },
  {
    bab: 35,
    judul: "Lomba ke puncak angin",
    teks: "Arun berdiri lagi, kakinya masih gemetar. \"Peluit harus ditiup di puncak tertinggi saat fajar,\" katanya, \"tepat ketika angin pertama bangun.\" Fajar tinggal sebentar lagi. Kuda, rusa kutub, dan anjing-anjing husky berkumpul, siap membawamu secepat mungkin.",
    judulEn: "The race to the wind's peak",
    teksEn: "Arun stood again, his legs still trembling. \"The whistle must be blown on the highest peak at dawn,\" he said, \"just as the first wind wakes.\" Dawn was close. Horses, reindeer and huskies gathered, ready to carry you as fast as they could.",
    tugas: "Berpacu melewati semua gerbang sebelum fajar tiba.",
    tugasEn: "Race through every gate before dawn arrives.",
  },
  {
    bab: 36,
    judul: "Lolongan pertama",
    teks: "Di puncak, kamu meniup peluit. Kali ini suaranya jernih dan panjang. Kristal-kristal pecah menjadi debu cahaya, dan dari lembah terdengar lolongan pertama, lalu yang kedua, lalu seluruh kawanan bernyanyi. Angin utara bangun dan menari di atas salju. Kincir desa berputar lagi, dan Sela mengangkat lenteranya tinggi-tinggi sebagai salam.",
    judulEn: "The first howl",
    teksEn: "On the peak you blew the whistle. This time its sound was clear and long. The crystals broke into dust of light, and from the valley came the first howl, then a second, then the whole pack singing. The north wind woke and danced across the snow. The village windmills turned again, and Sela raised her lantern high in greeting.",
    tugas: "Kembalikan pecahan terakhir ke altar agar angin tidak pernah diam lagi.",
    tugasEn: "Return the last shard to the altar so the wind is never silent again.",
  },
];
